name: update-card-prices.yaml
on:
  schedule:
    - cron: "10 5 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://fantasymtg.vercel.app/api/updateCardPrices' \
          --header 'Authorization: Bearer ${{ secrets.INTERNAL_API_KEY }}'
